# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - datafiller2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Cambiado a 8.2 para coincidir con otros workflows

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'DATAFILLER/composer.json'

      - name: Update composer dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        working-directory: DATAFILLER
        run: |
          rm -f composer.lock
          composer install --prefer-dist --no-progress --no-dev --ignore-platform-reqs

      - name: Zip artifact for deployment
        working-directory: DATAFILLER
        run: zip -r release.zip ./* --exclude=vendor/phpunit/* --exclude=tests/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: DATAFILLER/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A05B058B902E4D429D1FBAA9C8DC281B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_01223734A04049EB8A2837CD4ADFA0EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E0E519A9327E43F7A9CE7CC6405D676D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'datafiller2'
          slot-name: 'Production'
          package: .
