name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Code to scan PHP files
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk code test DATAFILLER/ || true
